DROP TABLE IF EXISTS EVALUATION_RESULT;
DROP TABLE IF EXISTS ANSWER;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS OVERALL_AVERAGE;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ADMIN_DATA;

CREATE TABLE ADMIN_DATA
(
    AdminID INT PRIMARY KEY CHECK (AdminID > 0),
    AnswersAreViewable BIT DEFAULT 0 CHECK (AnswersAreViewable IN (0, 1)),
    -- BIT = BOOLEAN
    EvalsAreViewable BIT DEFAULT 1 CHECK (EvalsAreViewable IN (0, 1))
    -- BIT = BOOLEAN
);

CREATE TABLE ACCOUNT
(
    AccountID INT IDENTITY(1, 1) PRIMARY KEY CHECK (AccountID > 0),
    Username VARCHAR(30) CHECK (LEN(TRIM(Username)) > 0) NOT NULL,
    PasswordHash VARCHAR(254) CHECK (LEN(TRIM(PasswordHash)) > 0) NOT NULL,
    AdminID INT NOT NULL,
    FOREIGN KEY (AdminID) REFERENCES ADMIN_DATA(AdminID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE OVERALL_AVERAGE
(
    AccountID INT NOT NULL,
    Average NUMERIC(5, 2) CHECK (Average BETWEEN 0 AND 100) NOT NULL,
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
);

CREATE TABLE QUESTION
(
    QuestionID INT IDENTITY(1, 1) PRIMARY KEY CHECK (QuestionID > 0),
    Description VARCHAR(1000) CHECK (LEN(TRIM(Description)) > 0) NOT NULL,
    AdminID INT NOT NULL,
    FOREIGN KEY (AdminID) REFERENCES ADMIN_DATA(AdminID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE ANSWER
(
    QuestionID INT NOT NULL,
    AccountID INT NOT NULL,
    AnswerText VARCHAR(1000) NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES QUESTION(QuestionID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    PRIMARY KEY (QuestionID, AccountID)
);

CREATE TABLE EVALUATION_RESULT
(
    QuestionID INT NOT NULL,
    AccountID INT NOT NULL,
    EvalText VARCHAR(1000) NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES QUESTION(QuestionID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    PRIMARY KEY (QuestionID, AccountID)
);