DROP TABLE IF EXISTS EVALUATION_RESULT;
DROP TABLE IF EXISTS ANSWER;
DROP TABLE IF EXISTS QUESTION;
DROP TABLE IF EXISTS OVERALL_AVERAGE;
DROP TABLE IF EXISTS ACCOUNT;
DROP TABLE IF EXISTS ADMIN_DATA;

CREATE TABLE ADMIN_DATA
(
    AdminID INTEGER PRIMARY KEY CHECK (AdminID > 0),
    AnswersAreViewable INTEGER DEFAULT 0 CHECK (AnswersAreViewable IN (0, 1)),
    -- BINARY = INTEGER (0, 1)
    EvalsAreViewable INTEGER DEFAULT 1 CHECK (EvalsAreViewable IN (0, 1))
    -- BINARY = INTEGER (0, 1)
);

CREATE TABLE ACCOUNT
(
    AccountID INTEGER PRIMARY KEY CHECK (AccountID > 0),
    Username TEXT CHECK (LENGTH(TRIM(Username)) > 0 AND LENGTH(TRIM(Username)) <= 30) NOT NULL,
    PasswordHash TEXT CHECK (LENGTH(TRIM(PasswordHash)) > 0 AND LENGTH(TRIM(PasswordHash)) <= 254) NOT NULL,
    AdminID INTEGER NOT NULL,
    FOREIGN KEY (AdminID) REFERENCES ADMIN_DATA(AdminID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE OVERALL_AVERAGE
(
    AccountID INTEGER NOT NULL,
    Average REAL CHECK (Average BETWEEN 0 AND 100) NOT NULL,
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION
);

CREATE TABLE QUESTION
(
    QuestionID INTEGER PRIMARY KEY CHECK (QuestionID > 0),
    Description TEXT CHECK (LENGTH(TRIM(Description)) > 0 AND LENGTH(TRIM(Description)) <= 1000) NOT NULL,
    AdminID INTEGER NOT NULL,
    FOREIGN KEY (AdminID) REFERENCES ADMIN_DATA(AdminID)
        ON DELETE NO ACTION
        ON UPDATE NO ACTION
);

CREATE TABLE ANSWER
(
    QuestionID INTEGER NOT NULL,
    AccountID INTEGER NOT NULL,
    AnswerText TEXT CHECK (LENGTH(TRIM(AnswerText)) > 0) NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES QUESTION(QuestionID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    PRIMARY KEY (QuestionID, AccountID)
);

CREATE TABLE EVALUATION_RESULT
(
    QuestionID INTEGER NOT NULL,
    AccountID INTEGER NOT NULL,
    EvalText TEXT NOT NULL,
    FOREIGN KEY (QuestionID) REFERENCES QUESTION(QuestionID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    FOREIGN KEY (AccountID) REFERENCES ACCOUNT(AccountID)
        ON DELETE CASCADE
        ON UPDATE NO ACTION,
    PRIMARY KEY (QuestionID, AccountID)
);